import Head from 'next/head';
import Image from 'next/image';
import getConfig from 'next/config';

import styles from 'src/styles/Home.module.css';

const { publicRuntimeConfig } = getConfig();
const { NODE_ENV } = publicRuntimeConfig;

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Image
          src="/nextjs-logo.svg"
          alt="Next.js logo"
          width={120}
          height={70}
        />
        <div>Environment: {NODE_ENV}</div>
      </main>
    </div>
  );
};

export default Home;
