import Head from 'next/head';
import getConfig from 'next/config';
import styles from 'src/styles/Home.module.css';

const { publicRuntimeConfig } = getConfig();
const { NODE_ENV } = publicRuntimeConfig;

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div>Environment: {NODE_ENV}</div>
      </main>
    </div>
  );
};

export default Home;
